#include "led.h"

// From ws2812_rgb example
#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/clocks.h"
#include "ws2812.pio.h"

// From ws2812_rgb example
#define IS_RGBW true        // Will use RGBW format
#define NUM_PIXELS 1        // There is 1 WS2812 device in the chain
#define WS2812_PIN 28       // The GPIO pin that the WS2812 connected to



/**
 * @brief Function given in ws2812_rgb example to call
 *        PIO function used to set color.
 * 
 * @param pixel_grb The 32-bit colour value generated by urgb_u32()
 */
static inline void put_pixel(uint32_t pixel_grb) {
    pio_sm_put_blocking(pio0, 0, pixel_grb << 8u);
}


/**
 * @brief Function given in ws2812_rgb example used to generate 
 *        an unsigned 32-bit composit GRB value
 * 
 * @param r     The 8-bit intensity value for the red component
 * @param g     The 8-bit intensity value for the green component
 * @param b     The 8-bit intensity value for the blue component
 * @return uint32_t Returns the resulting composit 32-bit RGB value
 */
static inline uint32_t urgb_u32(uint8_t r, uint8_t g, uint8_t b) {
    return  ((uint32_t) (r) << 8)  |
            ((uint32_t) (g) << 16) |
            (uint32_t) (b);
}


/**
 * @brief Function to initialise to NeoPixel RGB LED
 */

void led_init(){
 
    // To initialise basic IO
    stdio_init_all();
 
    // Initialise the PIO interface with the WS2812 code
    PIO pio = pio0;
    uint offset = pio_add_program(pio, &ws2812_program);
    ws2812_program_init(pio, 0, offset, WS2812_PIN, 800000, IS_RGBW);
}


void led_set_color(color led_color){

    // Set color to red
    if(led_color == red){
        put_pixel(urgb_u32(0x2F, 0x00, 0x00));  
    }

    // Set color to green
    else if(led_color == green){
        put_pixel(urgb_u32(0x00, 0x2F, 0x00));
    }

    // Set color to blue
    else if(led_color == blue){
        put_pixel(urgb_u32(0x00, 0x00, 0x2F));

    }

    // Set color to orange
    else if(led_color == orange){
        put_pixel(urgb_u32(0x2F, 0xC, 0x00));

    }

    // Set color to yellow
    else if(led_color == yellow){
        put_pixel(urgb_u32(0x2F, 0x25, 0x00));

    }
}


void led_disable()
{
    // Used to turn off the color on the NeoPixel RGB LED
    put_pixel(urgb_u32(0x00, 0x00, 0x00));
}
